// Real page/components in offline Chrome. Every network request is intercepted.
import {build} from 'esbuild';import{createRequire}from'node:module';import{readFile,mkdir}from'node:fs/promises';import assert from'node:assert/strict';
const require=createRequire(import.meta.url);const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Users/shinthantaungstanley/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const XLSX=require('xlsx');
async function workbook(page,kind,width){const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export Excel',exact:true}).click();const download=await pending;const file='.stock-history-test/browser/'+kind+'-'+width+'.xlsx';await download.saveAs(file);const book=XLSX.readFile(file);return XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]]);}
await mkdir('.stock-history-test/browser',{recursive:true});
const mock=`export const supabase={async rpc(name,args={}){window.calls.push({name,args});if(window.fail)return{error:{message:'Connection failed'},data:null};if(window.failExport&&args.p_limit===1000)return{error:{message:'Export unavailable'},data:null};
 const has_access=!window.noAccess;
 if(name==='stock_history_options'){const options={products:[{value:'p1',label:'Socks with a very long readable product name'},{value:'p2',label:'Gloves'}],locations:[{value:'store:a',label:'Authorized Store Alpha'}],people:[{value:'owner',label:'Another person'}],types:[{value:'transfer_dispatch',label:'Transfer Dispatch'}]}[args.p_kind]||[];const rows=has_access?options.filter(o=>o.label.toLowerCase().includes(args.p_query.toLowerCase())):[];return{data:{rows,total:rows.length,has_access}};}
 if(name==='stock_transfer_details')return{data:{status:'in_transit',destination:'Authorized Store Alpha',lines:[],notes:[{id:'1',stage:'Request',author:'Assigned Staff',at:'2020-01-01T02:00:00Z',text:'Please send the products'},{id:'2',stage:'Dispatch',author:'Owner',at:'2020-01-02T02:00:00Z',text:'Packed and sent today'}]}};
 const base=[{id:'m1',product_id:'p1',product_name:'Socks with a very long readable product name',product_sku:'SOCK',movement_type:'transfer_dispatch',type_label:'Transfer Dispatch',from_name:'Counterpart Warehouse',to_name:'Authorized Store Alpha',quantity:7,by_name:'Another person',notes:'Historical needle',transfer_request_id:'request',created_at:'2020-01-01T02:00:00Z'}];
 let rows=has_access?base.filter(r=>!args.p_filters.search||r.notes.toLowerCase().includes(args.p_filters.search.toLowerCase())):[];
 if(name==='stock_history_table')rows=has_access?[{product_id:'p1',product_name:base[0].product_name,product_sku:'SOCK',location_key:'store:a',location_name:'Authorized Store Alpha',opening_balance:null,inbound:7,outbound:0,closing_balance:20,in_transit_incoming:4,in_transit_outgoing:0,warning:'Opening balance unknown: complete inventory observations began later.',other_movement_net:13}]:[];
 return{data:{rows,total:rows.length,has_access,as_of:'2020-02-01T00:00:00Z'}};
}};`;
const result=await build({stdin:{contents:`import React from'react';import{createRoot}from'react-dom/client';import Page from'./src/pages/StockMovementsPage';createRoot(document.getElementById('root')).render(<Page/>);`,resolveDir:process.cwd(),loader:'tsx'},bundle:true,write:false,format:'iife',plugins:[{name:'offline',setup(b){b.onResolve({filter:/(?:^|\/)supabase$/},()=>({path:'db',namespace:'mock'}));b.onResolve({filter:/\.css$/},()=>({path:'css',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:a.path==='db'?mock:'',loader:'js'}));}}]});
const css=(await readFile('src/styles/globals.css','utf8')+'\n'+await readFile('src/components/stock-history/stock-history.css','utf8')).replace(/^@import.*$/gm,'');
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
try{for(const width of [1280,320,390]){const page=await browser.newPage({viewport:{width,height:900}});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',r=>r.request().url()==='https://stock.test/'?r.fulfill({contentType:'text/html',body:'<html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><main style="padding:14px"><div id="root"></div></main></body></html>'}):r.abort());await page.goto('https://stock.test/');await page.evaluate(()=>{window.calls=[];window.fail=false;window.noAccess=false;});await page.addStyleTag({content:css});await page.addScriptTag({content:result.outputFiles[0].text});
 await page.getByText('1 matching movements',{exact:false}).waitFor();
 const historyBook=await workbook(page,'history',width);assert.equal(historyBook.length,1);assert.equal(historyBook[0]['Source'],'Counterpart Warehouse');assert.equal(historyBook[0]['Quantity (units)'],7);assert.ok(historyBook[0]['Report filters and dates'].includes('Asia/Singapore'));
 await page.evaluate(()=>{window.failExport=true;});await page.getByRole('button',{name:'Export Excel',exact:true}).click();await page.getByRole('alert').filter({hasText:'Export failed: Export unavailable'}).waitFor();await page.evaluate(()=>{window.failExport=false;});
 await page.getByRole('button',{name:'Products',exact:true}).click();await page.getByRole('checkbox',{name:'Socks with a very long readable product name'}).check();await page.getByRole('checkbox',{name:'Gloves',exact:true}).check();await page.getByRole('button',{name:'Done',exact:true}).click();
 assert.equal(await page.evaluate(()=>document.activeElement.textContent),'Products (2)');await page.keyboard.press('Enter');await page.getByRole('checkbox',{name:'Gloves',exact:true}).waitFor();assert.equal(await page.getByRole('checkbox').count(),2);await page.keyboard.press('Escape');
 await page.getByLabel('Search stock history',{exact:true}).fill('needle');await page.waitForFunction(()=>window.calls.some(c=>c.args.p_filters?.search==='needle'&&c.args.p_filters.products.length===2));
 await page.getByRole('tab',{name:'Table',exact:true}).click();await page.getByText('Actual opening',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Remove Gloves from Products'}).count(),1);
 const tableBook=await workbook(page,'table',width);assert.equal(tableBook[0]['Actual opening (units)'],'Unknown / not applicable');assert.equal(tableBook[0]['Actual closing (units)'],20);assert.equal(tableBook[0]['Filtered inbound (units)'],7);assert.ok(tableBook[0]['Reconciliation warning'].includes('unknown'));
 await page.getByRole('tab',{name:'Table',exact:true}).focus();await page.keyboard.press('ArrowLeft');await page.getByRole('tab',{name:'History',exact:true}).waitFor();assert.equal(await page.getByRole('tab',{name:'History',exact:true}).getAttribute('aria-selected'),'true');await page.keyboard.press('ArrowRight');await page.getByText('Actual opening',{exact:true}).waitFor();await page.screenshot({path:'.stock-history-test/browser/table-'+width+'.png',fullPage:true});
 await page.getByRole('button',{name:'Clear search',exact:true}).click();await page.waitForFunction(()=>window.calls.at(-1).args.p_filters?.search==='');assert.equal(await page.getByRole('button',{name:'Remove Gloves from Products'}).count(),1);
 await page.getByRole('button',{name:'View movements',exact:true}).click();await page.getByRole('button',{name:'Transfer details & notes',exact:true}).click();await page.getByText('Packed and sent today',{exact:true}).waitFor();assert.equal(await page.getByText('Please send the products',{exact:true}).count(),1);await page.screenshot({path:'.stock-history-test/browser/notes-'+width+'.png'});await page.keyboard.press('Escape');
 // Modal can also be closed using its native close button if Escape is unused.
 if(await page.getByText('Transfer details and notes',{exact:true}).count())await page.locator('.modal-header button').click();
 await page.getByRole('button',{name:'Clear filters',exact:true}).click();await page.getByLabel('Search stock history',{exact:true}).fill('needle');await page.waitForFunction(()=>window.calls.at(-1).args.p_filters?.search==='needle');await page.getByRole('button',{name:'Clear filters',exact:true}).click();assert.equal(await page.getByLabel('Search stock history',{exact:true}).inputValue(),'needle');
 await page.getByRole('button',{name:'Locations',exact:true}).click();await page.getByRole('checkbox',{name:'Authorized Store Alpha'}).waitFor();assert.ok(await page.locator('body').evaluate(e=>e.scrollWidth<=window.innerWidth+1),'Filters caused page overflow');await page.keyboard.press('Escape');
 await page.screenshot({path:'.stock-history-test/browser/history-'+width+'.png'});
 await page.evaluate(()=>{window.fail=true;});await page.getByRole('button',{name:'Refresh',exact:true}).click();await page.getByRole('alert').filter({hasText:'Connection failed'}).waitFor();assert.equal(await page.getByRole('button',{name:'Export Excel',exact:true}).isDisabled(),true);
 await page.evaluate(()=>{window.fail=false;window.noAccess=true;});await page.getByRole('button',{name:'Retry',exact:true}).click();await page.getByText('You have no current store assignment.',{exact:false}).waitFor();assert.deepEqual(errors,[]);console.log('PASS actual Stock History controls, tab/filter preservation, shared notes, failures and no assignment at '+width+'px');await page.close();}}
finally{await browser.close();}
